
function presentacion(){
  var cont = '<h2>Revisión del autoestudio y validación de pares de los Programas Institucionales de Tutoría.</h2>'+
              '<div class="avance">'+
                '<p>Porcentaje de avance: 20% completado</p>'+
                '<div class="barra"><span class="color veinte"></span></div>'+
              '</div>'+
              '<article class="">'+
                '<p>'+
                  'Dentro de las principales acciones para lograr los objetivos de las Instituciones de Educación Superior (IES), los Programas Institucionales de Tutoría (PIT) representan un eje importante a considerar; aspectos tales como el rezago educativo, la deserción escolar, la adherencia al programa, el sano desarrollo emocional y sobre todo la calidad académica tienen en la tutoría una base sólida. Una forma de lograr que las IES tengan estos programas en desarrollo y con los mejores estándares de calidad, son los procesos de mejora continua.'+
                '</p>'+
                '<p>'+
                  'El proceso de revisión de la autoevaluación consiste en leer las respuestas, analizarlas y después escribir puntos importantes a destacar de acuerdo al formulario de autoevaluación presentado por el Representante de la IES interesada en ser evaluada, fue diseñado bajo una metodología de investigación – acción; es decir, con fines netamente de generar reflexiones sobre las condiciones actuales que tienen específicamente los PIT, con miras a implementar, actualizar y corregir aquellas áreas que pudieran ser susceptibles de una mejora continua.'+
                '</p>'+
                '<p>'+
                  'El diseño de este modelo se basa en los fundamentos de los Sistemas de Gestión de Calidad (SGC) propiamente de los modelos ISO 9001 y aplicado a las experiencias en el ambiente educativo (Buendía, 2013; Díaz, 2013 y Montes, 2002).'+
                '</p>'+
                '<p>'+
                  'La estructura del documento está dividida en siete ejes con un total de 33 rubros a analizar distribuidos de la siguiente forma:'+
                '</p>'+
              '</article>'+
              '<img src="../img/ejes.png" alt="Ejes autoevaluación PIT" title="Ejes autoevaluacion PIT" width="500px" height="auto">';

  var contenido = document.getElementById("contenido");
  contenido.innerHTML = cont;
}

function eje1(){
  var cont="";
  cont += "<h2>Fundamentos y condiciones de operación</h2>";
  cont += '        <div class="avance">';
  cont += '           <p>Porcentaje de avance: 40% completado</p>';
  cont += '           <div class="barra"><span class="color cuarenta"></span></div>';
  cont += '        </div>';
  cont += "        <div class=\"botones-save\">";
  cont += "          <button type=\"button\" name=\"button\" class=\"btn btn-save\"><i class=\"fas fa-save\"></i> Guardar</button>";
  cont += "        </div>";
  cont += "        <!--Agregar form-->";
  cont += "        <section class=\"formulario\" id=\"formulario1.1\">";
  cont += "          <h4 class=\"subeje obligatorio\">1.1 Entendimiento de la IES y su contexto</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"1.1.a.1\">Describa la ubicación y zona geográfica: </label>";
  cont += "          <label for=\"1.1.a.1\" class=\"respuesta\">La Universidad del Valle de Atemajac se encuentra en la Av. Tepeyac #4800, Col. Jardines del Tepeyac, en el municipio de Zapopan que se encuentra dentro de la zona geográfica 'A'. </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.1.a.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.1.a.2\">Carácter: </label>";
  cont += "          <label for=\"1.1.a.2\" class=\"respuesta\">Público </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.1.a.2\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.1.a.3\">Antigüedad de la IES: </label>";
  cont += "          <label for=\"1.1.a.3\" class=\"respuesta\">57 Años</label>";
  cont += "          <label for=\"1.1.a.3\" class=\"etiquetaComent\">Comentarios: </label>";
  cont += "          <label for=\"1.1.a.3\" class=\"comentarioEjem\">Especificar fecha de fundación.</label>";
  cont += "          <label for=\"1.1.a.3\" class=\"etiquetaResp\">Escribe una respuesta </label>";
  cont += "          <textarea class=\"comentarioResp\" name=\"comentario\" id=\"1.1.a.3\" placeholder=\"Escribir respuesta...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.1.a.3\" class=\"etiquetaComent\">Agregue un comentario </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.2.a.2\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.1.a.4\">Misión: </label>";
  cont += "          <label for=\"1.1.a.4\" class=\"respuesta\">Formar líderes con espíritu de servicio y comprometidos con el bien común. </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.1.a.4\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.1.a.5\">Visión: </label>";
  cont += "          <label for=\"1.1.a.5\" class=\"respuesta\">Somos un sistema universitario eficiente, sustentable y congruente con su identidad católica. </label>";
  cont += "          <label for=\"1.1.a.5\" class=\"etiquetaComent\">Comentarios: </label>";
  cont += "          <label for=\"1.1.a.5\" class=\"comentarioEjem\">Explicar mejor la visión de la institución.</label>";
  cont += "          <label for=\"1.1.a.5\" class=\"etiquetaResp\">Escribe una respuesta </label>";
  cont += "          <textarea class=\"comentarioResp\" name=\"comentario\" id=\"1.1.a.5\" placeholder=\"Escribir respuesta...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.1.a.5\" class=\"etiquetaComent\">Agregue un comentario </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.1.a.5\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.1.a.6\">Valores: </label>";
  cont += "          <label for=\"1.1.a.6\" class=\"respuesta\">I. Perseverancia <br>II. Solidaridad <br>III. Lealtad <br>IV. Justicia <br>V. Honestidad <br>VI. Respeto </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.1.a.6\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <div class=\"botones-documento\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn btn-doc\"><i class=\"fas fa-folder-open\"></i>  Ver documentos</button>";
  cont += "          </div>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.1.b.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"1.1.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <label for=\"1.1.c.1\" class=\"respuesta\"> N/A </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.1.c.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "        </section>";
  cont += "";
  cont += "        <section class=\"formulario\" id=\"formulario1.2\">";
  cont += "          <h4 class=\"subeje obligatorio\">1.2 Entendimiento de la IES y su contexto (Parte 2)</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"1.2.a.1\">¿Cómo le llaman al programa en la institución? </label>";
  cont += "          <label for=\"1.2.a.1\" class=\"respuesta\">Programa Institucional de Tutoría</label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.2.a.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.2.a.2\">¿Por qué le llaman así? </label>";
  cont += "          <label for=\"1.2.a.2\" class=\"respuesta\">Porque es un nombre adecuado y formal con el fin de englobar todos los procesos relacionados a las Tutorías.</label>";
  cont += "          <label for=\"1.2.a.2\" class=\"etiquetaComent\">Comentarios: </label>";
  cont += "          <label for=\"1.2.a.2\" class=\"comentarioEjem\">Explicar específicamente porqué se elegió el nombre del PIT y cuáles son los procesos que engloba.</label>";
  cont += "          <label for=\"1.2.a.2\" class=\"respuestaEjem\">No es necesario explicar los procesos que engloba.</label>";
  cont += "          <label for=\"1.2.a.2\" class=\"etiquetaResp\">Escribe una respuesta </label>";
  cont += "          <textarea class=\"comentarioResp\" name=\"comentario\" id=\"1.2.a.2\" placeholder=\"Escribir respuesta...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.2.a.2\" class=\"etiquetaComent\">Agregue un comentario </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.2.a.2\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <div class=\"botones-documento\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn btn-doc\"><i class=\"fas fa-folder-open\"></i>  Ver documentos</button>";
  cont += "          </div>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.2.b.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"1.2.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <label for=\"1.2.c.1\" class=\"respuesta\"> N/A </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.2.c.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "        </section>";
  cont += "";
  cont += "        <section class=\"formulario\" id=\"formulario1.3\">";
  cont += "          <h4 class=\"subeje obligatorio\">1.3 Cobertura </h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"1.3.a.1\">Número de alumnos: </label>";
  cont += "          <label for=\"1.3.a.1\" class=\"respuesta\">13000 Alumnos</label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.3.a.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.3.a.2\">Número de tutores en la IES: </label>";
  cont += "          <label for=\"1.3.a.2\" class=\"respuesta\">6000 Tutores</label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.3.a.2\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.3.a.3\">Proporción de alumnos atendidos por tutor: </label>";
  cont += "          <label for=\"1.3.a.3\" class=\"respuesta\">3 %</label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.3.a.3\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.3.a.4\">Porcentaje de alumnos atendidos: </label>";
  cont += "          <label for=\"1.3.a.4\" class=\"respuesta\">95 %</label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.3.a.4\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.3.a.5\">De acuerdo a los datos obtenidos describa si la cobertura de alumnos en su IES en qué medida es suficiente y por qué. </label>";
  cont += "          <label for=\"1.3.a.5\" class=\"respuesta\">Es suficiente porque se cubre el 95% de los alumnos, ya que hay algunos estudiantes que no asisten a sus sesiones de tutoría, para este problema ya se está realizando una solución.</label>";
  cont += "          <label for=\"1.3.a.5\" class=\"etiquetaComent\">Comentarios: </label>";
  cont += "          <label for=\"1.3.a.5\" class=\"comentarioEjem\">Explicar específicamente la solución al problema de inasistencia de alumnos a sus sesiones de Tutorías.</label>";
  cont += "          <label for=\"1.3.a.5\" class=\"respuestaEjem\">Además, indicar desde cuándo se realiza esta solución.</label>";
  cont += "          <label for=\"1.3.a.5\" class=\"respuestaEjem\">Se debe especificar si la solución está proporcionando resultados.</label>";
  cont += "          <label for=\"1.3.a.5\" class=\"etiquetaResp\">Escribe una respuesta </label>";
  cont += "          <textarea class=\"comentarioResp\" name=\"comentario\" id=\"1.3.a.5\" placeholder=\"Escribir respuesta...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.3.a.5\" class=\"comentarioEjem\">Realizar encuestas a alumnos sobre la solución al problema de inasistencia.</label>";
  cont += "          <label for=\"1.3.a.5\" class=\"respuestaEjem\">También, encuestas sobre la opinión en general del programa de Tutorías.</label>";
  cont += "          <label for=\"1.3.a.5\" class=\"etiquetaResp\">Escribe una respuesta </label>";
  cont += "          <textarea class=\"comentarioResp\" name=\"comentario\" id=\"1.3.a.5\" placeholder=\"Escribir respuesta...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"1.3.a.5\" class=\"etiquetaComent\">Agregue un comentario </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.3.a.5\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <div class=\"botones-documento\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn btn-doc\"><i class=\"fas fa-folder-open\"></i>  Ver documentos</button>";
  cont += "          </div>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.3.b.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"1.3.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <label for=\"1.3.c.1\" class=\"respuesta\"> N/A </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.3.c.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "        </section>";
  cont += "";
  cont += "        <section class=\"formulario\" id=\"formulario1.4\">";
  cont += "          <h4 class=\"subeje opcional\">1.4 Opcional </h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"1.4.a.1\">Describa si existe algún otro elemento importante que describa el contexto de la IES: </label>";
  cont += "          <label for=\"1.4.a.1\" class=\"respuesta\">Constantemente se renuevan carreras y planes de estudio. Así como se resuelven problemáticas de la comunidad, profesores y alumnos.</label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.4.a.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <div class=\"botones-documento\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn btn-doc\"><i class=\"fas fa-folder-open\"></i>  Ver documentos</button>";
  cont += "          </div>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.4.b.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"1.4.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <label for=\"1.4.c.1\" class=\"respuesta\"> N/A </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"1.4.c.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "        </section>";
  cont += "        <div class=\"botones-save\">";
  cont += "          <button type=\"button\" name=\"button\" class=\"btn btn-save\"><i class=\"fas fa-save\"></i> Guardar</button>";
  cont += "        </div>";

  var contenido = document.getElementById("contenido");
  contenido.innerHTML = cont;
}

function eje2(){
  var cont="";
  cont += "<h2>Gobierno y liderazgo</h2>";
  cont += '        <div class="avance">';
  cont += '           <p>Porcentaje de avance: 30% completado</p>';
  cont += '           <div class="barra"><span class="color treinta"></span></div>';
  cont += '        </div>';
  cont += "        <!--Agregar form-->";
  cont += "        <div class=\"botones-save\">";
  cont += "          <button type=\"button\" name=\"button\" class=\"btn btn-save\"><i class=\"fas fa-save\"></i> Guardar</button>";
  cont += "        </div>";
  cont += "        <section class=\"formulario\" id=\"formulario2.1\">";
  cont += "          <h4 class=\"subeje obligatorio\">2.1 Roles, responsabilidades y autoridades</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"2.1.a.1\">Describa desde dónde opera el programa institucional de tutoría: </label>";
  cont += "          <label for=\"2.1.a.1\" class=\"respuesta\">Opera desde la Universidad del Valle de Atemajac.</label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.1.a.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"2.1.a.2\">En dónde se integra en el organigrama de la institución: </label>";
  cont += "          <label for=\"2.1.a.2\" class=\"respuesta\">En el puesto de responsable del Programa Institucional de Tutoría de la Universidad del Valle de Atemajac.</label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.1.a.2\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"2.1.a.3\">Detalle los roles y responsabilidades de la alta dirección  (consejo universitario, consejo directivo, dirección general, junta de gobierno o rectoría) así como de la secretaría académica, planeación o estructuras similares.</label>";
  cont += "          <label for=\"2.1.a.3\" class=\"respuesta\">1. Consejo universitario: Verificar que los tutores y tutorados cumplan con sus labores correspondientes y corregir cualquier problema disciplinal o que incumpla con lo establecido. <br>2. Consejo directivo: Crea y actualiza nuevos métodos para la ejecución del Programa Institucional de Tutoría. <br>3. Dirección general: Resuelve conflictos menores correspondientes a tutores o tutorados. <br>4. Rectoría: Aprueba y supervisa el trabajo del organigrama inferior, para garantizar que las responsabilidades son ejecutadas satisfactoriamente. <br>5. Secretaría académica: Supervisa el trabajo de tutores con respecto a las necesidades de los tutorados. Les brinda a los alumnos el medio para comunicar sus inquietudes y problemas.  </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.1.a.3\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "          <label for=\"2.1.a.4\">¿Cómo opera a nivel de las entidades académicas y con qué otras áreas se coordina para operar en cada programa educativo?</label>";
  cont += "          <label for=\"2.1.a.4\" class=\"respuesta\">El programa institucional de tutoría opera llevando a cabo un registro de las actividades que se realizan entre tutor y tutorado, situaciones de relevancia y solución de problemas.</label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.1.a.4\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <div class=\"botones-documento\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn btn-doc\"><i class=\"fas fa-folder-open\"></i>  Ver documentos</button>";
  cont += "          </div>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.1.b.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"2.1.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <label for=\"2.1.c.1\" class=\"respuesta\"> N/A </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.1.c.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "        </section>";
  cont += "        <section class=\"formulario\" id=\"formulario2.2\">";
  cont += "          <h4 class=\"subeje obligatorio\">2.2 Marco normativo</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"2.2.a.1\">Indicar los marcos de referencia formales que dan sustento al PIT en su institución tanto, nacionales, estatales o locales (modelo educativo, modelo académico, guías de diseño o rediseño curricular, normatividad institucional, plan de desarrollo, reglamentos, planes institucionales, políticas nacionales, estatales, etcétera).</label>";
  cont += "          <label for=\"2.2.a.1\" class=\"respuesta\">Los marcos de referencia que dan sustento al PIT son: <br>1. Modelo educativo. <br>2. Modelo académico. <br>3. Plan de desarrollo. <br>4. Reglamentos.</label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.1.a.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <div class=\"botones-documento\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn btn-doc\"><i class=\"fas fa-folder-open\"></i>  Ver documentos</button>";
  cont += "          </div>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.2.b.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"2.2.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <label for=\"2.2.c.1\" class=\"respuesta\"> N/A </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.2.c.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "        </section>";
  cont += "        <section class=\"formulario\" id=\"formulario2.3\">";
  cont += "          <h4 class=\"subeje obligatorio\">2.3 Políticas de calidad</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"2.3.a.1\">Describir cómo miden la efectividad del programa de tutoría.</label>";
  cont += "          <label for=\"2.3.a.1\" class=\"respuesta\">Se mide mediante estadísticas cálculadas según el número de tutores y tutorados y su efectividad.</label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.3.a.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <div class=\"botones-documento\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn btn-doc\"><i class=\"fas fa-folder-open\"></i>  Ver documentos</button>";
  cont += "          </div>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.3.b.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"2.3.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <label for=\"2.3.c.1\" class=\"respuesta\"> N/A </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.3.c.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "        </section>";
  cont += "        <section class=\"formulario\" id=\"formulario2.4\">";
  cont += "          <h4 class=\"subeje obligatorio\">2.4 Finanzas</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"2.4.a.1\">Mencione si existe un presupuesto asignado especialmente para la operación del programa de tutorías tanto a nivel central como en las entidades académicas y en qué medida éste es suficiente para operar el programa. </label>";
  cont += "          <label for=\"2.4.a.1\" class=\"respuesta\">Sí, hay un presupuesto asignado para la operación del programa de tutoría. Es suficiente para operar el programa ya que, permite realizar actividades para beneficio de los involucrados.</label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.4.a.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <div class=\"botones-documento\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn btn-doc\"><i class=\"fas fa-folder-open\"></i>  Ver documentos</button>";
  cont += "          </div>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.4.b.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"2.4.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <label for=\"2.4.c.1\" class=\"respuesta\"> N/A </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.4.c.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "        </section>";
  cont += "        <section class=\"formulario\" id=\"formulario2.5\">";
  cont += "          <h4 class=\"subeje opcional\">2.5 Opcional</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"2.5.a.1\">Describa si existe algún otro elemento importante que detalle la forma de gobierno y liderazgo.</label>";
  cont += "          <label for=\"2.5.a.1\" class=\"respuesta\">Los tutores asisten a cursos de liderazgo, por lo que están mejor capacitados.</label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.5.a.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <div class=\"botones-documento\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn btn-doc\"><i class=\"fas fa-folder-open\"></i>  Ver documentos</button>";
  cont += "          </div>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.5.b.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"2.5.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <label for=\"2.5.c.1\" class=\"respuesta\"> N/A </label>";
  cont += "          <textarea class=\"comentario\" name=\"comentario\" id=\"2.5.c.1\" placeholder=\"Agregar comentario...\"></textarea>";
  cont += "          <div class=\"btn_comentar\">";
  cont += "           <button type=\"button\" name=\"button\" class=\"btn teartiary\"> Enviar</button>";
  cont += "          </div>";
  cont += "        </section>";
  cont += "        <div class=\"botones-save\">";
  cont += "          <button type=\"button\" name=\"button\" class=\"btn btn-save\"><i class=\"fas fa-save\"></i> Guardar</button>";
  cont += "        </div>";

  var contenido = document.getElementById("contenido");
  contenido.innerHTML = cont;
}

function eje3(){
  var cont="";
  cont += "<h2>Planificación</h2>";
  cont += "        <!--Agregar form-->";
  cont += "        <div class=\"botones-save\">";
  cont += "          <button type=\"button\" name=\"button\" class=\"btn btn-save\"><i class=\"fas fa-save\"></i> Guardar</button>";
  cont += "        </div>";
  cont += "        <section class=\"formulario\" id=\"formulario3.1\">";
  cont += "          <h4 class=\"subeje obligatorio\">3.1 Acciones para la determinación de factores de riesgo y de oportunidades</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"3.1.a.1\">Describa si cuenta con un proceso para diagnosticar las necesidades, para operar el PIT y las necesidades de los estudiantes que permitan planear las metas y acciones para mejorar el rendimiento y la eficiencia terminal de sus estudiantes. </label>";
  cont += "          <textarea name=\"procesoDiag\" id=\"3.1.a.1\" placeholder=\"Describir proceso...\"></textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"3.1.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"3.1.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"3.1.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"3.1.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "";
  cont += "        <section class=\"formulario\" id=\"formulario3.2\">";
  cont += "          <h4 class=\"subeje obligatorio\">3.2 Objetivos y planes para alcanzarlos</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"descripcion\" style=\"width:100%;\"> Describa los siguientes aspectos que inciden en su programa de tutorías: <br/></label>";
  cont += "          <label for=\"3.2.a.1\">Ejes estratégicos: </label>";
  cont += "          <textarea name=\"ejesEstra\" id=\"3.2.a.1\" placeholder=\"Ejes estratégicos...\"></textarea>";
  cont += "          <label for=\"3.2.a.2\">Programas estratégicos: </label>";
  cont += "          <textarea name=\"programasEstra\" id=\"3.2.a.2\" placeholder=\"Programas estratégicos...\"></textarea>";
  cont += "          <label for=\"3.2.a.3\">Objetivos: </label>";
  cont += "          <textarea name=\"objetivos\" id=\"3.2.a.3\" placeholder=\"Objetivos...\"></textarea>";
  cont += "          <label for=\"3.2.a.4\">Metas: </label>";
  cont += "          <textarea name=\"metas\" id=\"3.2.a.4\" placeholder=\"Metas...\"></textarea>";
  cont += "          <label for=\"3.2.a.5\">Acciones: </label>";
  cont += "          <textarea name=\"acciones\" id=\"3.2.a.5\" placeholder=\"Acciones...\"></textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"3.2.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"3.2.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"3.2.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"3.2.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "";
  cont += "        <section class=\"formulario\" id=\"formulario3.3\">";
  cont += "          <h4 class=\"subeje deseable\">3.3 Planificación de cambios</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"descripcion\" style=\"width:100%;\"> Describa si han implementado los aspectos siguientes para apoyar el desarrollo de competencias genéricas y específicas para el ejercicio de la tutoría: <br/></label>";
  cont += "          <label for=\"3.3.a.1\">Nuevos enfoques para el acompañamiento tutorial de los estudiantes: </label>";
  cont += "          <textarea name=\"enfoquesTut\" id=\"3.3.a.1\" placeholder=\"Enfoques...\"></textarea>";
  cont += "          <label for=\"3.3.a.2\">Cambios en la normatividad de estudiantes y profesores: </label>";
  cont += "          <textarea name=\"normatividad\" id=\"3.3.a.2\" placeholder=\"Normatividad...\"></textarea>";
  cont += "          <label for=\"3.3.a.3\">Cambios en su programa de capacitación, formación y actualización de tutores: </label>";
  cont += "          <textarea name=\"cambiosTutores\" id=\"3.3.a.3\" placeholder=\"Cambios realizados...\"></textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"3.3.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"3.3.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"3.3.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"3.3.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "";
  cont += "        <section class=\"formulario\" id=\"formulario3.4\">";
  cont += "          <h4 class=\"subeje opcional\">3.4 Opcional </h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"3.4.a.1\">Describa si existe algún otro aspecto importante relacionado con planificación. <br/>Por ejemplo, si han incluido tendencias relacionadas con Responsabilidad Social Universitaria, Cultura de la legalidad, enfoque a grupos vulnerables, cuidado del medio ambiente o sustentabilidad.</label>";
  cont += "          <textarea name=\"aspectoPlan\" id=\"3.4.a.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"3.4.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"3.4.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"3.4.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"3.4.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "        <div class=\"botones-save\">";
  cont += "          <button type=\"button\" name=\"button\" class=\"btn btn-save\"><i class=\"fas fa-save\"></i> Guardar</button>";
  cont += "        </div>";

  var contenido = document.getElementById("contenido");
  contenido.innerHTML = cont;
}

function eje4(){
  var cont="";
  cont += "<h2>Soporte</h2>";
  cont += "        <!--Agregar form-->";
  cont += "        <div class=\"botones-save\">";
  cont += "          <button type=\"button\" name=\"button\" class=\"btn btn-save\"><i class=\"fas fa-save\"></i> Guardar</button>";
  cont += "        </div>";
  cont += "";
  cont += "        <section class=\"formulario\" id=\"formulario4.1\">";
  cont += "          <h4 class=\"subeje obligatorio\">4.1 Recursos humanos: Perfil</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"4.1.a.1\">Describa cuál es el perfil y las principales funciones de los tutores que operan el PIT</label>";
  cont += "          <textarea name=\"descripcion\" id=\"4.1.a.1\" placeholder=\"Descripción...\"></textarea>";
  cont += "          <label for=\"4.1.a.2\">Describa cómo eligen a los tutores y si este proceso garantiza contar con el personal adecuado para operar el programa y los alcances establecidos por su institución.</label>";
  cont += "          <textarea name=\"descripcion\" id=\"4.1.a.2\" placeholder=\"Descripción...\"></textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"4.1.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"4.1.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"4.1.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"4.1.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "        <section class=\"formulario\" id=\"formulario4.2\">";
  cont += "          <h4 class=\"subeje obligatorio\">4.2 Recursos humanos: Formación</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"4.2.a.1\">Describa las acciones para realizar la inducción, formación, sensibilización y capacitación de los tutores enfocados a la acción tutorial y en qué momento se realizan.</label>";
  cont += "          <textarea name=\"descripcion\" id=\"4.2.a.1\" placeholder=\"Descripción...\"></textarea>";
  cont += "          <label for=\"4.2.a.2\">Indique si existe un mecanismo de evaluación de la formación de los tutores y cómo opera.</label>";
  cont += "          <textarea name=\"descripcion\" id=\"4.2.a.2\" placeholder=\"Descripción...\"></textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"4.2.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"4.2.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"4.2.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"4.2.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "        <section class=\"formulario\" id=\"formulario4.3\">";
  cont += "          <h4 class=\"subeje obligatorio\">4.3 Infraestructura</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"4.3.a.1\">Describa si la institución cuenta con espacios destinados especialmente para la tutoría y si éstos son suficientes para la adecuada operación del programa.</label>";
  cont += "          <textarea name=\"descripcion\" id=\"4.3.a.1\" placeholder=\"Descripción...\"></textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"4.3.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"4.3.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"4.3.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"4.3.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "        <section class=\"formulario\" id=\"formulario4.4\">";
  cont += "          <h4 class=\"subeje obligatorio\">4.4 Tecnología y comunicación</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"4.4.a.1\">Describa el uso de medios tradicionales y electrónicos enfocados a tareas de registro, documentación y consulta de información de la acción tutorial del PIT en su institución para el seguimiento, evaluación, indicadores de calidad y toma de decisiones</label>";
  cont += "          <textarea name=\"descripcion\" id=\"4.4.a.1\" placeholder=\"Descripción...\"></textarea>";
  cont += "          <label for=\"4.4.a.2\">Mencione qué medios se utilizan y cómo se realiza la comunicación entre los diferentes actores y niveles del PIT resaltando la comunicación con los alumnos.</label>";
  cont += "          <textarea name=\"descripcion\" id=\"4.4.a.2\" placeholder=\"Descripción...\"></textarea>";
  cont += "          <label for=\"4.4.a.3\">Mencioné las innovaciones implementadas en los últimos años en cuanto a tecnología y comunicación y si en qué medida han aportado mejoras al PIT.</label>";
  cont += "          <textarea name=\"descripcion\" id=\"4.4.a.3\" placeholder=\"Descripción...\"></textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"4.4.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"4.4.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"4.4.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"4.4.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "        <section class=\"formulario\" id=\"formulario4.5\">";
  cont += "          <h4 class=\"subeje obligatorio\">4.5 Documentación</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"4.5.a.1\">Mencione los recursos y materiales de apoyo para el trabajo con estudiantes y el tutor; formatos que dan cuenta del proceso en la trayectoria escolar y la función del tutor y otros actores del PIT. Si es el caso, el diseño de cuadernillos, manuales, etcétera.</label>";
  cont += "          <textarea name=\"descripcion\" id=\"4.5.a.1\" placeholder=\"Descripción...\"></textarea>";
  cont += "";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"4.5.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"4.5.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"4.5.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"4.5.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "        <section class=\"formulario\" id=\"formulario4.6\">";
  cont += "          <h4 class=\"subeje deseable\">4.6 Innovación</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"4.6.a.1\">Mencione si la IES ha realizado algún proceso de innovación que revolucione el programa de tutoría en el último año; por ejemplo, la incorporación de nuevas actividades relacionadas con las megatendencias, grandes cambios sociales, económicos o culturales.</label>";
  cont += "          <textarea name=\"descripcion\" id=\"4.6.a.1\" placeholder=\"Descripción...\"></textarea>";
  cont += "          <label for=\"4.6.a.2\">Si existe alguna política al respecto y cómo ha impactado en la mejora continua del programa.</label>";
  cont += "          <textarea name=\"descripcion\" id=\"4.6.a.2\" placeholder=\"Descripción...\"></textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"4.6.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"4.6.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"4.6.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"4.6.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "        <section class=\"formulario\" id=\"formulario4.7\">";
  cont += "          <h4 class=\"subeje deseable\">4.7 Soporte</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"4.7.a.1\">Describa si existe algún otro aspecto relevante a mencionar en cuanto a soporte del programa de tutoría.</label>";
  cont += "          <textarea name=\"descripcion\" id=\"4.7.a.1\" placeholder=\"Descripción...\"></textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"4.7.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"4.7.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"4.7.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"4.7.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "";
  cont += "        <div class=\"botones-save\">";
  cont += "          <button type=\"button\" name=\"button\" class=\"btn btn-save\"><i class=\"fas fa-save\"></i> Guardar</button>";
  cont += "        </div>";

  var contenido = document.getElementById("contenido");
  contenido.innerHTML = cont;
}

function eje5(){
  var cont="";
  cont += "<h2>Operación</h2>";
  cont += "        <!--Agregar form-->";
  cont += "        <div class=\"botones-save\">";
  cont += "          <button type=\"button\" name=\"button\" class=\"btn btn-save\"><i class=\"fas fa-save\"></i> Guardar</button>";
  cont += "        </div>";
  cont += "        <section class=\"formulario\" id=\"formulario5.1\">";
  cont += "          <h4 class=\"subeje obligatorio\">5.1 Procesos</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"descripcion\" style=\"width:100%;\"> Enuncie si la IES cuenta con diagramas de los diferentes procesos tales como: <br/></label>";
  cont += "          <label for=\"5.1.a.1\">a. Procesos de formación de tutores: </label>";
  cont += "          <textarea name=\"procesoTut\" id=\"5.1.a.1\" placeholder=\"Describir proceso...\"></textarea>";
  cont += "          <label for=\"5.1.a.2\">b. Procesos de asignación de tutores a estudiantes: </label>";
  cont += "          <textarea name=\"procesoTutEst\" id=\"5.1.a.2\" placeholder=\"Describir proceso...\"></textarea>";
  cont += "          <label for=\"5.1.a.3\">c. Procesos de evaluación del PIT: </label>";
  cont += "          <textarea name=\"procesoEvPIT\" id=\"5.1.a.3\" placeholder=\"Describir proceso...\"></textarea>";
  cont += "          <label for=\"5.1.a.4\">d. Procesos para evaluar el impacto de la tutoría en indicadores institucionales y la formación integral de los estudiantes: </label>";
  cont += "          <textarea name=\"procesoEvTut\" id=\"5.1.a.4\" placeholder=\"Describir proceso...\"></textarea>";
  cont += "          <label for=\"5.1.a.5\">e. Otros procesos propios para la operación del PIT: </label>";
  cont += "          <textarea name=\"procesoOpePIT\" id=\"5.1.a.5\" placeholder=\"Describir proceso...\"></textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"5.1.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"5.1.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"5.1.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"5.1.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "";
  cont += "        <section class=\"formulario\" id=\"formulario5.2\">";
  cont += "          <h4 class=\"subeje obligatorio\">5.2 Seguimiento</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"5.2.a.1\">Describa cómo se da el seguimiento al total de alumnos: </label>";
  cont += "          <textarea name=\"seguimientoAlum\" id=\"5.2.a.1\" placeholder=\"Descripción...\"></textarea>";
  cont += "          <label for=\"5.2.a.2\">¿Cómo se aseguran que los alumnos tutorados reciban el servicio que se documenta en el apartado de procesos? </label>";
  cont += "          <textarea name=\"AlumTut\" id=\"5.2.a.2\" placeholder=\"Descripción...\"></textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"5.2.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"5.2.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"5.2.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"5.2.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "";
  cont += "        <section class=\"formulario\" id=\"formulario5.3\">";
  cont += "          <h4 class=\"subeje obligatorio\">5.3 Registro de avances, metas o logros</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"5.3.a.1\">Describir los mecanismos para documentar los avances: </label>";
  cont += "          <textarea name=\"mecanismoAvan\" id=\"5.3.a.1\" placeholder=\"Mecanismos...\"></textarea>";
  cont += "          <label for=\"5.3.a.2\">¿Cómo estos son utilizados para el control del programa? </label>";
  cont += "          <textarea name=\"control\" id=\"5.3.a.2\" placeholder=\"Descripción...\"></textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"5.3.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"5.3.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"5.3.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"5.3.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "";
  cont += "        <section class=\"formulario\" id=\"formulario5.4\">";
  cont += "          <h4 class=\"subeje opcional\">5.4 Operación del Programa</h4>";
  cont += "          <h5 >A) Descripción</h5>";
  cont += "          <label for=\"5.4.a.1\">Describa si existe algún otro aspecto relevante a mencionar en cuanto a la operación del programa de tutoría: </label>";
  cont += "          <textarea name=\"aspectoOpe\" id=\"5.4.a.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos</h5>";
  cont += "          <label class=\"lab-documentos\" for=\"5.4.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)</label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"5.4.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional</h5>";
  cont += "          <label for=\"5.4.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.</label>";
  cont += "          <textarea name=\"adicional\" id=\"5.4.c.1\" placeholder=\"Información adicional...\"></textarea>";
  cont += "        </section>";
  cont += "        <div class=\"botones-save\">";
  cont += "          <button type=\"button\" name=\"button\" class=\"btn btn-save\"><i class=\"fas fa-save\"></i> Guardar</button>";
  cont += "        </div>";

  var contenido = document.getElementById("contenido");
  contenido.innerHTML = cont;
}

function eje6(){
  var cont="";
  cont += "        <h2>Evaluación del desempeño<\/h2>";
  cont += "        <!--Agregar form-->";
  cont += "        <div class=\"botones-save\">";
  cont += "          <button type=\"button\" name=\"button\" class=\"btn btn-save\"><i class=\"fas fa-save\"><\/i> Guardar<\/button>";
  cont += "        <\/div>";
  cont += "        <section class=\"formulario\" id=\"formulario6.1\">";
  cont += "          <h4 class=\"subeje obligatorio\">6.1 Seguimiento, medición, análisis y evaluación<\/h4>";
  cont += "          <h5 >A) Descripción<\/h5>";
  cont += "          <label for=\"\" style=\"width: 100%;\">Describa las acciones de los principales actores para medir, analizar y evaluar el PIT. Evaluación vista como rendición de cuentas de todos los actores y niveles involucrados.<\/label>";
  cont += "          <label for=\"6.1.a.1\">Alta dirección: Como responsables directivos del PIT.<\/label>";
  cont += "          <textarea name=\"descripcion\" id=\"6.1.a.1\" placeholder=\"Descripción...\"><\/textarea>";
  cont += "          <label for=\"6.1.a.2\">Mandos medios: Responsables ejecutivos del PIT y\/o coordinadores en las áreas.<\/label>";
  cont += "          <textarea name=\"descripcion\" id=\"6.1.a.2\" placeholder=\"Descripción...\"><\/textarea>";
  cont += "          <label for=\"6.1.a.3\">Operativos: Los tutores, asesores, monitores, psicopedagogos o psicólogos.<\/label>";
  cont += "          <textarea name=\"descripcion\" id=\"6.1.a.3\" placeholder=\"Descripción...\"><\/textarea>";
  cont += "          <label for=\"6.1.a.4\">Tutorados: Sobre el servicio recibido como beneficiario.<\/label>";
  cont += "          <textarea name=\"descripcion\" id=\"6.1.a.4\" placeholder=\"Descripción...\"><\/textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos<\/h5>";
  cont += "          <label class=\"lab-documentos\" for=\"6.1.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)<\/label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"6.1.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional<\/h5>";
  cont += "          <label for=\"6.1.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.<\/label>";
  cont += "          <textarea name=\"adicional\" id=\"6.1.c.1\" placeholder=\"Información adicional...\"><\/textarea>";
  cont += "        <\/section>";
  cont += "        <section class=\"formulario\" id=\"formulario6.2\">";
  cont += "          <h4 class=\"subeje obligatorio\">6.2 Indicadores cuantitativos<\/h4>";
  cont += "          <h5 >A) Descripción<\/h5>";
  cont += "          <label for=\"6.2.a.1\">Describa si la IES cuenta con un modelo de evaluación cuantitativa o sistema de indicadores de desempeño tales como: deserción, ausentismo, reprobación, efectividad, entre otros que dan muestra cuantitativamente del desempeño del PIT.<\/label>";
  cont += "          <textarea name=\"descripcion\" id=\"6.2.a.1\" placeholder=\"Descripción...\"><\/textarea>";
  cont += "          <label for=\"6.2.a.2\">Describa cómo esta información es utilizada para la mejora continua del PIT.<\/label>";
  cont += "          <textarea name=\"descripcion\" id=\"6.2.a.2\" placeholder=\"Descripción...\"><\/textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos<\/h5>";
  cont += "          <label class=\"lab-documentos\" for=\"6.2.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)<\/label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"6.2.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional<\/h5>";
  cont += "          <label for=\"6.2.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.<\/label>";
  cont += "          <textarea name=\"adicional\" id=\"6.2.c.1\" placeholder=\"Información adicional...\"><\/textarea>";
  cont += "        <\/section>";
  cont += "        <section class=\"formulario\" id=\"formulario6.3\">";
  cont += "          <h4 class=\"subeje obligatorio\">6.3 Indicadores cualitativos<\/h4>";
  cont += "          <h5 >A) Descripción<\/h5>";
  cont += "          <label for=\"6.3.a.1\">Describa el mecanismo para recolectar datos cualitativos del desempeño del programa y cómo estos se utilizan para la mejora continua.<\/label>";
  cont += "          <textarea name=\"descripcion\" id=\"6.3.a.1\" placeholder=\"Descripción...\"><\/textarea>";
  cont += "          <label for=\"6.3.a.2\">En este apartado puede mencionar si cuentan con indicadores que den cuenta de aspectos tales como atención de conductas de riesgo, problemas de salud mental, orientación vocacional, seguridad, grupos vulnerables, comunidades, indígenas o tendencias propias del contexto en que opera la IES y cómo son integrados para la mejora del PIT.<\/label>";
  cont += "          <textarea name=\"descripcion\" id=\"6.3.a.2\" placeholder=\"Descripción...\"><\/textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos<\/h5>";
  cont += "          <label class=\"lab-documentos\" for=\"6.3.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)<\/label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"6.3.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional<\/h5>";
  cont += "          <label for=\"6.3.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.<\/label>";
  cont += "          <textarea name=\"adicional\" id=\"6.3.c.1\" placeholder=\"Información adicional...\"><\/textarea>";
  cont += "        <\/section>";
  cont += "        <section class=\"formulario\" id=\"formulario6.4\">";
  cont += "          <h4 class=\"subeje deseable\">6.4 Auditoria interna<\/h4>";
  cont += "          <h5 >A) Descripción<\/h5>";
  cont += "          <label for=\"6.4.a.1\">Describa si la IES cuenta con un proceso de auditoria interna para evaluar el PIT.<\/label>";
  cont += "          <textarea name=\"descripcion\" id=\"6.4.a.1\" placeholder=\"Descripción...\"><\/textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos<\/h5>";
  cont += "          <label class=\"lab-documentos\" for=\"6.4.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)<\/label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"6.4.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional<\/h5>";
  cont += "          <label for=\"6.4.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.<\/label>";
  cont += "          <textarea name=\"adicional\" id=\"6.4.c.1\" placeholder=\"Información adicional...\"><\/textarea>";
  cont += "        <\/section>";
  cont += "        <section class=\"formulario\" id=\"formulario6.4\">";
  cont += "          <h4 class=\"subeje opcional\">6.5 Opcional<\/h4>";
  cont += "          <h5 >A) Descripción<\/h5>";
  cont += "          <label for=\"6.5.a.1\">Describa si cuentan con algún otro método de evaluación alternativa al programa de tutorías.<\/label>";
  cont += "          <textarea name=\"descripcion\" id=\"6.5.a.1\" placeholder=\"Descripción...\"><\/textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos<\/h5>";
  cont += "          <label class=\"lab-documentos\" for=\"6.5.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)<\/label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"6.5.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional<\/h5>";
  cont += "          <label for=\"6.5.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.<\/label>";
  cont += "          <textarea name=\"adicional\" id=\"6.5.c.1\" placeholder=\"Información adicional...\"><\/textarea>";
  cont += "        <\/section>";
  cont += "";
  cont += "        <div class=\"botones-save\">";
  cont += "          <button type=\"button\" name=\"button\" class=\"btn btn-save\"><i class=\"fas fa-save\"><\/i> Guardar<\/button>";
  cont += "        <\/div>";

  var contenido = document.getElementById("contenido");
  contenido.innerHTML = cont;
}

function eje7(){
  var cont="";
  cont += "<h2>Mejora continua<\/h2>";
  cont += "        <!--Agregar form-->";
  cont += "        <div class=\"botones-save\">";
  cont += "          <button type=\"button\" name=\"button\" class=\"btn btn-save\"><i class=\"fas fa-save\"><\/i> Guardar<\/button>";
  cont += "        <\/div>";
  cont += "        <section class=\"formulario\" id=\"formulario7.1\">";
  cont += "          <h4 class=\"subeje obligatorio\">7.1 No conformidades y acción correctiva <\/h4>";
  cont += "          <h5 >A) Descripción<\/h5>";
  cont += "          <label for=\"7.1.a.1\">Describa si cuentan con un mecanismo para documentar las inconformidades: <\/label>";
  cont += "          <textarea name=\"inconformidad\" id=\"7.1.a.1\" placeholder=\"Describir mecanismo...\"><\/textarea>";
  cont += "          <label for=\"7.1.a.2\">¿Cuál es la forma de corregir y prevenir las inconformidades? <\/label>";
  cont += "          <textarea name=\"corregirIncon\" id=\"7.1.a.2\" placeholder=\"Describir proceso...\"><\/textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos<\/h5>";
  cont += "          <label class=\"lab-documentos\" for=\"7.1.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)<\/label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"7.1.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional<\/h5>";
  cont += "          <label for=\"7.1.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.<\/label>";
  cont += "          <textarea name=\"adicional\" id=\"7.1.c.1\" placeholder=\"Información adicional...\"><\/textarea>";
  cont += "        <\/section>";
  cont += "";
  cont += "        <section class=\"formulario\" id=\"formulario7.2\">";
  cont += "          <h4 class=\"subeje obligatorio\">7.2 Mejora continua<\/h4>";
  cont += "          <h5 >A) Descripción<\/h5>";
  cont += "          <label for=\"7.2.a.1\">Describir cómo la IES utiliza los indicadores de desempeño para mejora continua del programa: <\/label>";
  cont += "          <textarea name=\"mejoraCont\" id=\"7.2.a.1\" placeholder=\"Descripción...\"><\/textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos<\/h5>";
  cont += "          <label class=\"lab-documentos\" for=\"7.2.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)<\/label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"7.2.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional<\/h5>";
  cont += "          <label for=\"7.2.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.<\/label>";
  cont += "          <textarea name=\"adicional\" id=\"7.2.c.1\" placeholder=\"Información adicional...\"><\/textarea>";
  cont += "        <\/section>";
  cont += "";
  cont += "        <section class=\"formulario\" id=\"formulario7.3\">";
  cont += "          <h4 class=\"subeje deseable\">7.3 Investigación y actualización<\/h4>";
  cont += "          <h5 >A) Descripción<\/h5>";
  cont += "          <label for=\"7.3.a.1\">Describa si la IES cuenta con proyectos de investigación sobre tutoría: <\/label>";
  cont += "          <textarea name=\"proyectosTut\" id=\"7.3.a.1\" placeholder=\"Descripción...\"><\/textarea>";
  cont += "          <label for=\"7.3.a.2\">¿Éstos son usados para la mejora continua y la divulgación del conocimiento científico entre los actores del PIT? <\/label>";
  cont += "          <textarea name=\"usoProyectos\" id=\"7.3.a.2\" placeholder=\"Descripción...\"><\/textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos<\/h5>";
  cont += "          <label class=\"lab-documentos\" for=\"7.3.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)<\/label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"7.3.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional<\/h5>";
  cont += "          <label for=\"7.3.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.<\/label>";
  cont += "          <textarea name=\"adicional\" id=\"7.3.c.1\" placeholder=\"Información adicional...\"><\/textarea>";
  cont += "        <\/section>";
  cont += "";
  cont += "        <section class=\"formulario\" id=\"formulario7.4\">";
  cont += "          <h4 class=\"subeje opcional\">7.4 Opcional<\/h4>";
  cont += "          <h5 >A) Descripción<\/h5>";
  cont += "          <label for=\"7.4.a.1\">Describa si cuentan con algún otro elemento que aporte a la mejora continua del PIT: <\/label>";
  cont += "          <textarea name=\"otroElem\" id=\"7.4.a.1\" placeholder=\"Descripción...\"><\/textarea>";
  cont += "";
  cont += "          <h5 >B) Documentos<\/h5>";
  cont += "          <label class=\"lab-documentos\" for=\"7.4.b.1\"><i class=\"far fa-file-alt\"></i> Adjuntar documentos (en caso de existir)<\/label>";
  cont += "          <input class=\"documentos\" type=\"file\" name=\"documentos\" id=\"7.4.b.1\" value=\"\">";
  cont += "";
  cont += "          <h5 >C) Información adicional<\/h5>";
  cont += "          <label for=\"7.4.c.1\">Información adicional que deberá estar disponible, en versión impresa o preferentemente electrónica, durante la visita de pares.<\/label>";
  cont += "          <textarea name=\"adicional\" id=\"7.4.c.1\" placeholder=\"Información adicional...\"><\/textarea>";
  cont += "        <\/section>";
  cont += "        <div class=\"botones-save\">";
  cont += "          <button type=\"button\" name=\"button\" class=\"btn btn-save\"><i class=\"fas fa-save\"><\/i> Guardar<\/button>";
  cont += "        <\/div>";

  var contenido = document.getElementById("contenido");
  contenido.innerHTML = cont;
}
